/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Composition = IDL.Record({
  'midiData' : IDL.Vec(IDL.Nat8),
  'title' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'getComposition' : IDL.Func([IDL.Text], [Composition], ['query']),
  'listCompositions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'saveComposition' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Composition = IDL.Record({
    'midiData' : IDL.Vec(IDL.Nat8),
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'getComposition' : IDL.Func([IDL.Text], [Composition], ['query']),
    'listCompositions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'saveComposition' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };