/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Composition = IDL.Record({
  'midiData' : IDL.Vec(IDL.Nat8),
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const Note = IDL.Text;
export const Fingering = IDL.Vec(IDL.Bool);
export const OcarinaFingeringConfig = IDL.Record({
  'name' : IDL.Text,
  'instrumentType' : IDL.Text,
  'fingerings' : IDL.Vec(IDL.Tuple(Note, Fingering)),
});

export const idlService = IDL.Service({
  'getComposition' : IDL.Func([IDL.Nat], [Composition], ['query']),
  'getFingeringDefaults' : IDL.Func([], [OcarinaFingeringConfig], ['query']),
  'listCompositions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Composition))],
      ['query'],
    ),
  'resetFingeringDefaults' : IDL.Func([], [], []),
  'saveComposition' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [IDL.Nat],
      [],
    ),
  'setFingeringDefaults' : IDL.Func([OcarinaFingeringConfig], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Composition = IDL.Record({
    'midiData' : IDL.Vec(IDL.Nat8),
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const Note = IDL.Text;
  const Fingering = IDL.Vec(IDL.Bool);
  const OcarinaFingeringConfig = IDL.Record({
    'name' : IDL.Text,
    'instrumentType' : IDL.Text,
    'fingerings' : IDL.Vec(IDL.Tuple(Note, Fingering)),
  });
  
  return IDL.Service({
    'getComposition' : IDL.Func([IDL.Nat], [Composition], ['query']),
    'getFingeringDefaults' : IDL.Func([], [OcarinaFingeringConfig], ['query']),
    'listCompositions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Composition))],
        ['query'],
      ),
    'resetFingeringDefaults' : IDL.Func([], [], []),
    'saveComposition' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [IDL.Nat],
        [],
      ),
    'setFingeringDefaults' : IDL.Func([OcarinaFingeringConfig], [], []),
  });
};

export const init = ({ IDL }) => { return []; };