/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Composition {
  'midiData' : Uint8Array,
  'title' : string,
  'description' : string,
}
export type Fingering = Array<boolean>;
export type Note = string;
export interface OcarinaFingeringConfig {
  'name' : string,
  'instrumentType' : string,
  'fingerings' : Array<[Note, Fingering]>,
}
export interface _SERVICE {
  'getComposition' : ActorMethod<[bigint], Composition>,
  'getFingeringDefaults' : ActorMethod<[], OcarinaFingeringConfig>,
  'listCompositions' : ActorMethod<[], Array<[bigint, Composition]>>,
  'resetFingeringDefaults' : ActorMethod<[], undefined>,
  'saveComposition' : ActorMethod<[string, string, Uint8Array], bigint>,
  'setFingeringDefaults' : ActorMethod<[OcarinaFingeringConfig], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];